### ISSUE TITLE
Fatal error with Gutenberg 2.9

### ISSUE THREAD

**Issue by robertdevore** [Ultimate-Blocks/Ultimate-Blocks#1]
I just updated Gutenberg to version 2.9 and am now met with the following error:

`Fatal error: Uncaught Error: Call to undefined function register_block_type() in /srv/www/gutenberg/public_html/wp-content/plugins/ultimate-blocks/src/blocks/click-to-tweet/block.php:64`

link to line in the file [here](https://github.com/imtiazrayhan/Ultimate-Blocks/blob/master/src/blocks/click-to-tweet/block.php#L64)

**Comment by imtiazrayhan** [comment]
Hi Robert,

I just updated to Gutenberg 2.9.1 and it seems to be working. I don't see the Fatal error. 

This could happen if by any chance you have the Gutenberg plugin deactivated. If Gutenberg is not activated, the function becomes undefined.

Please check if that's the issue.

**Comment by robertdevore** [comment]
I have Gutenberg installed - the error happened during the upgrade to 2.9.0

I haven't checked with 2.9.1, but will test it again.

**Comment by imtiazrayhan** [comment]
Please let me know here if you see the issue with 2.9.1 too.
