### ISSUE TITLE
Issue with acf block in content-toggle and content-tab modules

### ISSUE THREAD

**Issue by midhundevasia** [Ultimate-Blocks/Ultimate-Blocks#15]
Web have many issues with acf block plugin and ultimate-block in combination. 
1. There are too many warning showing like 
 ```
react.js:401 Warning: Each child in a list should have a unique "key" prop.
 Check the top-level render call using <svg>. See https://fb.me/react-warning-keys for more information.
    in rect
```
`react-dom.js:82 Warning: Cannot update a component (`UnsavedChangesWarning`) while rendering a different component (`c`). To locate the bad setState() call inside `c`, follow the stack trace as described in`

`react-dom.js:82 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
`
`react-dom.js:82 Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.`

All these warnings are only after activating ultimate block

2. Bug in 2nd time editing a ACF block field in multiple accordion or tabs. Sometime the first accordion content is able to edit. and the other accordion contents are not editable. when switching to preview its not getting updated the new values. in the backend of frontend. Ultimate block with default gutenburg block are working fine. on firsttime and 2nd time browser reload. But there is an issue with ACF block, but the ACF block alone is working fine. But in combination with Ultimate Accordion its not working properly.

**Comment by erdembircan** [comment]
Issue is solved with later updates.
