### ISSUE TITLE
Tabbed Content block Bold and Italic buttons issue

### ISSUE THREAD

**Issue by RavanH** [Ultimate-Blocks/Ultimate-Blocks#2]
Hi,

It seems the Bold and Italic editor buttons only affect the tab titles, not the tab content.

A screen film can be seen here https://status301.net/wp-content/uploads/2018/10/Schermfilm-van-02-10-18-181447.webm

**Comment by imtiazrayhan** [comment]
Thank you for reporting that.

I will fix it as soon as possible.

**Comment by aqib-git** [comment]
@RavanH 

I have fixed this issue download the latest version of this plugin. It should work now.

**Comment by RavanH** [comment]
Yes, fix tested and confirmed :) will it be in version 1.0.6 ?

**Comment by imtiazrayhan** [comment]
> Yes, fix tested and confirmed :) will it be in version 1.0.6 ?

Yes. I am releasing the update today.
