### ISSUE TITLE
Blocks do not render properly, plugin code is not loading when pull content from one page into another.

### ISSUE THREAD

**Issue by michellecurran** [Ultimate-Blocks/Ultimate-Blocks#24]
When pull content from one page into another page, the ultimate blocks do not render properly.   All the html for the 2 pages are exactly the same.  The only difference I can find between the 2 pages is that the Ultimate Blocks plugin code is not loading for the duplicated page.   

I am using the Tabbed Content block on this page, but I get the same behavior for any Ultimate block.

Original Page:
https://events-mec-upenn-sp2.pantheonsite.io/program/master-of-science-in-nonprofit-leadership/

Duplicated Page:
https://events-mec-upenn-sp2.pantheonsite.io/academics/ms-in-nonprofit-leadership/inquiry/

I am looking for some guidance on why this is happening and how I can get the Ultimate Blocks code to load in this case.

**Comment by Alexius08** [comment]
Hi Michelle! Further inspection reveals that the Ultimate Blocks CSS file didn't load in the duplicate page. Thus, the blocks themselves appear in the duplicate page without any styling at all.

The plugin's PHP code allows the CSS file to be loaded only when [at least one block from the plugin has been detected on the page](https://github.com/Ultimate-Blocks/Ultimate-Blocks/blob/2ddebc480e715c85134c3ec86b0a9bd25e62ae5c/src/init.php#L137). Whatever you used to duplicate the page recreated the page in a way that rendered the blocks undetectable to the PHP file. For now, you can bypass this by manually linking to the CSS file. We may be able to investigate this issue further if you share how you duplicated the page.

**Comment by michellecurran** [comment]
Thank you.  Here is the template for the page.   It is displaying content for the post ID of the duplicated page.

```
`<?php
	/**
	 * The template for displaying a program
	 *
	 * @package sp2
	 * @since 1.0.0
	 */

	get_header();

?>
  <main class="full-width-container">
    <div>
        <?php

					// get duplicated content acf fields
					$dupe_enabled = get_field('content_duplication_enabled');
					$dupe_post_id = get_field('content_duplication_from');

	        // check if this is a page with duplicated content from another page
					if ($dupe_enabled) :
						
						// get content for dupe page
						$content = get_the_content("", false, $dupe_post_id);

						// apply filter to get the same content that the_content would display and render
						echo apply_filters( 'the_content', $content );

					else:
						the_post();
						the_content();
					endif;

        ?>
    </div>
  </main><!-- #main -->

<?php
	get_footer();`
```

**Comment by michellecurran** [comment]
I am actually currently working in the branch that I gave you the link to, trying to figure out what files to load from the plugin, so you may see some changes if you look at the duped page.   I have it the tabbed content styling better, but it looks like it may be missing the click functionality, which I assume is javascript?  I really am not keen to hardcode this in, and I appreciate you taking a look at it.  We are going live on Friday and I need to get the page working today or tomorrow :)

**Comment by michellecurran** [comment]
Thank you Alexis.  Your initial response was incredibly helpful and I have created a workaround.  For the benefit of anyone else with this use case I will provide an explanation of my workaround.   I found that if I put the ultimate block on the page that will have the content from another page, let's call that the duped page, then the code will load. I am applying css to hide that block.  I tried to put that block code in a template part, but it only worked if it was placed on the page with the block editor. I also had to add some css for the tab tray block to cover the dynamically created css that includes the id of the block and therefore was not applying. I created a block pattern for the user to place on the duped page to make it more user friendly.  Below is the revised page template.

```
<?php
	/**
	 * The template for displaying a program
	 *
	 * @package sp2
	 * @since 1.0.0
	 */

	get_header();

?>
  <main class="full-width-container">
    <div>
        <?php ?>


<?php
					// get duplicated content acf fields
					$dupe_enabled = get_field('content_duplication_enabled');
					$dupe_post_id = get_field('content_duplication_from');

	        // check if this is a page with duplicated content from another page
					if ($dupe_enabled) :

						//ultimate blocks work around - if dupe page has tab tray or expand or any ultimate block then
						//a hidden block of same type must be  placed on page to trigger ultimate block code - this is
						//because ultimate block code only loads if detects blocks - tried putting code on backend
						//and triggering happens dynamically so doesn't work
						the_content();

						// get content for page that you are duping
						$content = get_the_content("", false, $dupe_post_id);

						// apply filter to get the same content that the_content would display and render
						echo apply_filters( 'the_content', $content );

					else:
						the_post();
						the_content();
					endif;

        ?>
    </div>
  </main><!-- #main -->

<?php
	get_footer();

```
