### ISSUE TITLE
Support align for tabbed content

### ISSUE THREAD

**Issue by oxyc** [Ultimate-Blocks/Ultimate-Blocks#5]
Would be great if the tabbed content block supported align wide and full. It also breaks when setting custom class

**Comment by Alexius08** [comment]
Hi @oxyc! We just released a new version that [adds the wide and full alignments to the tabbed content block](https://github.com/Ultimate-Blocks/Ultimate-Blocks/commit/90c4c18b8099de64238f1fc22215757543951628). Also, we've [fixed the issue with setting custom class names](https://github.com/Ultimate-Blocks/Ultimate-Blocks/commit/541daf2b23c3f47c878b403c4d973e2dc06b8c4d).
