### ISSUE TITLE
Demo links

### ISSUE THREAD

**Issue by WPbasics** [Ultimate-Blocks/Ultimate-Blocks#6]
Hello friends,

Just thought I would mention that it appears that your demo links for the Ultimate Blocks plugin is pointing to a local host.
BTW, great job on the plugin.

Regards,

José

**Comment by imtiazrayhan** [comment]
Hi @WPbasics, 

Thanks for reaching out here. We are really glad that you like the plugin.

Can you please share with me which links? The demo that we have in [demo.ultimateblocks.com](https://demo.ultimateblocks.com/) seems to be working.

Regards.

**Comment by WPbasics** [comment]
Hi,

These links are all broken.  It’s on your homepage ultimateblocks.com.
Regards,
José

[cid:image001.jpg@01D5172F.36568800]

**Comment by Alexius08** [comment]
The links in README.md redirect to localhost, while the ones under the Top Features section of the Ultimate Blocks home page go to localhost directly. I've fixed most of the broken links in the README file.

**Comment by imtiazrayhan** [comment]
Fixed the links on home page.
