### ISSUE TITLE
Making Ultimate Blocks "Reusable Blocks" doesn't include JavaScript files

### ISSUE THREAD

**Issue by jnschrag** [Ultimate-Blocks/Ultimate-Blocks#7]
Hi there!

I've been using Ultimate Blocks specifically for the "Expand" and "Content Toggle" block functionality. I noticed that if I make one of those blocks a "Reusable Block" with pre-filled out content, the UB JavaScript files aren't included when I view the published post. The CSS files are still included, it's just the JS files that are not.

Any help would be much appreciated!

**Comment by Alexius08** [comment]
Hi @jnschrag!

Thanks for bringing this to our attention. It has been fixed by adapting the code for including the CSS to deal with the frontend JS files. We'll include the fix on the next release.
