### ISSUE TITLE
Countdown Block shows extra preceding '1' when JS disabled or fails to execute

### ISSUE THREAD

**Issue by westonruter** [Ultimate-Blocks/Ultimate-Blocks#8]
When JS is disabled in the browser, or if the scripts used by the Countdown block fail to load, an extra `1` appears before each number. Compare JS-enabled on left and JS-disabled on right:

<img width="1354" alt="Screen Shot 2019-10-14 at 16 56 31" src="https://user-images.githubusercontent.com/134745/66790242-d0b34400-eea3-11e9-84b3-30f7c803b029.png">

This is also seen when the page is first loaded while waiting for the JS to initialize.

**Comment by Alexius08** [comment]
Hi @westonruter !

Thanks for letting us know. The code has been revised to remove the need for the extra 1s. It will be available on the next release.
