### ISSUE TITLE
URL in button block with a few parameters broken after duplicate page

### ISSUE THREAD

**Issue by marina9568** [Ultimate-Blocks/Ultimate-Blocks#9]
At first thank you for the plugin. 
I have a problem.
On my page I'm using button block with URL includes parameters like:
https://example.com/?client=567632&product=24668
Then I need to duplicate the page to use its content for next page.
But on new page button URL is broken. it looks like:
https://example.com/?client=567632u0026product=24668
I used a different plugins for duplicate post and problem is still the same. Then I made my own simple duplicate function using `wp_insert_post()` but problem repeats again. So I think that problem is on block's side.
Please, help me to deal with this.

**Comment by Alexius08** [comment]
Please [see this](https://wordpress.org/support/topic/url-in-button-block-with-a-few-parameters-broken-after-duplicate-page/#post-12190570) for a possible workaround.
